### ISSUE TITLE
ERROR in metadata, Unrecognized key: "inject-into".

### ISSUE THREAD

**Issue by ihavenoface** [SimonAlling/userscript-metadata#1]
This appears to be referring to the usage of https://violentmonkey.github.io/posts/inject-into-context/

Is there a reason this tag is not included?

**Comment by SimonAlling** [comment]
> Is there a reason this tag is not included?

Yes, the reason is that (according to [the page linked above](https://violentmonkey.github.io/posts/inject-into-context/)) it didn't exist until Violentmonkey v2.10.0, which [was released on December 1, 2018](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.10.0), whereas [the latest commit in this repo](https://github.com/SimonAlling/userscript-metadata/commit/0076cecf25c8f424ae888e4af5dfc0ba8f884453) was made on August 1 that year. :innocent: 

**It seems to me like it should be added.** In the meantime, you may be able to use `validateAndStringifyWith` and/or `readAndValidateWith` as a workaround, as described under [_Customization_](https://github.com/SimonAlling/userscript-metadata#customization) in the readme, although that depends on how you're using this library (e.g. indirectly via [Userscripter](https://github.com/SimonAlling/userscripter)). Hope you'll find the workaround useful; otherwise, please get back with more information. :slightly_smiling_face:

**Comment by z0mad** [comment]
@SimonAlling I am having the same problem with tampermonkeys "[connect](https://www.tampermonkey.net/documentation.php#_connect)", via Userscripter. Any suggestions of a workaround in this case?

**Comment by SimonAlling** [comment]
> @SimonAlling I am having the same problem with tampermonkeys "[connect](https://www.tampermonkey.net/documentation.php#_connect)", via Userscripter. Any suggestions of a workaround in this case?

Yes! Or maybe not so much a workaround as an actual solution that both Userscripter and userscript-metadata were designed to support: Userscripter's `createWebpackConfig` function lets the userscript author specify how the metadata should be validated. The patch below shows how `@connect` directives could be added in [Example Userscript](https://github.com/SimonAlling/example-userscript). If you clone that repo, you can even save the patch as a file and apply it using e.g. `git apply connect.patch`. :slightly_smiling_face: 

```patch
diff --git a/metadata.ts b/metadata.ts
index 64e25d5..e47d86a 100644
--- a/metadata.ts
+++ b/metadata.ts
@@ -17,6 +17,10 @@ export default function(buildConfig: BuildConfig): Metadata {
             `*://${U.hostname}/*`,
             `*://www.${U.hostname}/*`,
         ],
+        connect: [
+            "example.com",
+            "example.org",
+        ],
         namespace: U.namespace,
         run_at: U.runAt,
         ...(
diff --git a/webpack.config.ts b/webpack.config.ts
index 927f5f9..3b2994a 100644
--- a/webpack.config.ts
+++ b/webpack.config.ts
@@ -4,6 +4,7 @@ import {
     DEFAULT_BUILD_CONFIG,
     DEFAULT_METADATA_SCHEMA,
 } from "userscripter/build";
+import { StringItem } from "userscript-metadata";
 
 import MANIFEST from "./manifest";
 import METADATA from "./metadata";
@@ -23,6 +24,16 @@ export default createWebpackConfig({
     },
     manifest: MANIFEST,
     metadata: METADATA,
-    metadataSchema: DEFAULT_METADATA_SCHEMA,
+    metadataSchema: {
+        ...DEFAULT_METADATA_SCHEMA,
+        items: {
+            ...DEFAULT_METADATA_SCHEMA.items,
+            connect: new StringItem({
+                key: "connect",
+                required: false,
+                unique: false,
+            }),
+        },
+    },
     env: process.env,
 });
```

**Comment by SimonAlling** [comment]
Nevertheless, `@inject-into` and `@connect` (and possibly others) should probably be added to [the default items](https://github.com/SimonAlling/userscript-metadata/blob/master/src/data.ts#L17) in this library.

**Comment by SimonAlling** [comment]
There we go! @ihavenoface and @z0mad, `npm install userscript-metadata@^1.1.0` should do the trick! The workaround/solution I suggested above should not be necessary anymore. :slightly_smiling_face:

**Comment by ihavenoface** [comment]
Awesome, thanks a lot!
